[package]
name = "stream-semantic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
stream-model = { path = "../stream-model" }

[dev-dependencies]
chrono.workspace = true
url.workspace = true
