[package]
name = "stream-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
scraper.workspace = true
stream-ingest = { path = "../stream-ingest" }
stream-model = { path = "../stream-model" }
url.workspace = true
